const $=id=>document.getElementById(id); const state={mode:'gui',dataUrl:null,baseData:null};
const defaults={alpha:1,beta:0,gamma:1,blend:.5,blur:'none',kernel:3,sigmaX:0,sigmaY:0,bd:7,sc:75,ss:75,morph:'none',morphK:3,iter:1,thresholdMode:'none',th:127,maxv:255,block:11,cval:2,edge:'none',c1:80,c2:160,sobelK:3,ht:50,hmin:50,hgap:10,rmin:0,rmax:0,noise:0,dh:0,dhc:0,hueMin:0,hueMax:179,satMin:0,satMax:255,valMin:0,valMax:255,angle:0,scale:1,tx:0,ty:0,sf:1.1,mn:5,conf:50,nms:45};
const names={alpha:'Alpha',beta:'Beta',gamma:'Gamma',blend:'Blend',blur:'Blur',kernel:'Kernel',sigmaX:'Sigma X',sigmaY:'Sigma Y',bd:'Bilateral d',sc:'Sigma Color',ss:'Sigma Space',morph:'Morphology',morphK:'Morph kernel',iter:'Iterations',thresholdMode:'Threshold',th:'Threshold',maxv:'Max value',block:'Block size',cval:'C',edge:'Edge',c1:'Canny 1',c2:'Canny 2',sobelK:'Sobel',ht:'Hough threshold',hmin:'Min line length',hgap:'Max line gap',rmin:'Min radius',rmax:'Max radius',noise:'Noise',dh:'Denoise h',dhc:'hColor',hueMin:'Hue min',hueMax:'Hue max',satMin:'Sat min',satMax:'Sat max',valMin:'Value min',valMax:'Value max',angle:'Rotation',scale:'Scale',tx:'Translate X',ty:'Translate Y'};
function params(){let p={}; Object.keys(defaults).forEach(k=>{let e=$(k); p[k]=e?(e.type==='range'?Number(e.value):e.value):defaults[k]}); return p}
function codeFromParams(){const p=params();return `import cv2\nimport numpy as np\n\n# OpenCV Studio generated pipeline\nimg = img.copy()\nimg = cv2.convertScaleAbs(img, alpha=${p.alpha}, beta=${p.beta})\n${p.gamma!==1?`inv=1/${p.gamma}\ntable=np.array([((i/255.0)**inv)*255 for i in range(256)]).astype('uint8')\nimg=cv2.LUT(img,table)`:''}\n${p.blur==='gaussian'?`img=cv2.GaussianBlur(img, (${p.kernel}, ${p.kernel}), ${p.sigmaX}, ${p.sigmaY})`:p.blur==='median'?`img=cv2.medianBlur(img, ${p.kernel})`:p.blur==='bilateral'?`img=cv2.bilateralFilter(img, ${p.bd}, ${p.sc}, ${p.ss})`:''}\n${p.morph!=='none'?`ker=cv2.getStructuringElement(cv2.MORPH_RECT, (${p.morphK},${p.morphK}))\nimg=cv2.morphologyEx(img, cv2.MORPH_${p.morph.toUpperCase()}, ker, iterations=${p.iter})`:''}\n${p.thresholdMode==='binary'?`gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)\ngray=cv2.threshold(gray,${p.th},${p.maxv},cv2.THRESH_BINARY)[1]\nimg=cv2.cvtColor(gray,cv2.COLOR_GRAY2BGR)`:p.thresholdMode==='otsu'?`gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)\ngray=cv2.threshold(gray,0,${p.maxv},cv2.THRESH_BINARY+cv2.THRESH_OTSU)[1]\nimg=cv2.cvtColor(gray,cv2.COLOR_GRAY2BGR)`:p.thresholdMode==='adaptive'?`gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)\ngray=cv2.adaptiveThreshold(gray,${p.maxv},cv2.ADAPTIVE_THRESH_GAUSSIAN_C,cv2.THRESH_BINARY,${p.block},${p.cval})\nimg=cv2.cvtColor(gray,cv2.COLOR_GRAY2BGR)`:''}\n${p.edge==='canny'?`gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)\nimg=cv2.cvtColor(cv2.Canny(gray,${p.c1},${p.c2}),cv2.COLOR_GRAY2BGR)`:''}\n${p.noise>0?`img=np.clip(img.astype(np.float32)+np.random.normal(0,${p.noise},img.shape),0,255).astype(np.uint8)`:''}\n${p.dh>0?`img=cv2.fastNlMeansDenoisingColored(img,None,${p.dh},${p.dhc},7,21)`:''}\n${p.scale!==1?`img=cv2.resize(img,None,fx=${p.scale},fy=${p.scale},interpolation=cv2.INTER_CUBIC)`:''}\n${(p.angle||p.tx||p.ty)?`h,w=img.shape[:2]\nM=cv2.getRotationMatrix2D((w/2,h/2),${p.angle},1.0)\nM[0,2]+=${p.tx}; M[1,2]+=${p.ty}\nimg=cv2.warpAffine(img,M,(w,h),borderMode=cv2.BORDER_CONSTANT,borderValue=(20,20,20))`:''}\n\nresult = img`}
function updateOutputs(){document.querySelectorAll('output').forEach(o=>{const e=o.previousElementSibling||o; if(!e.id)return; let v=e.value; if(['alpha','gamma','blend','sf'].includes(e.id))v=Number(v).toFixed(2); if(e.id==='scale')v=Number(v).toFixed(1)+'×'; if(e.id==='angle')v+='°'; if(['conf','nms'].includes(e.id))v+='%'; o.textContent=v})}
async function render(){if(!state.dataUrl||!window.editorProcess)return;updateOutputs();const out=await window.editorProcess(JSON.stringify(params()));state.baseData=out;draw(out);buildPipe();$('codeEditor').value=codeFromParams();lines()}
function draw(src){const img=new Image();img.onload=()=>{const c=$('canvas');const maxW=c.parentElement.clientWidth*.94,maxH=c.parentElement.clientHeight*.94,s=Math.min(maxW/img.width,maxH/img.height,1);c.width=img.width;c.height=img.height;c.style.width=(img.width*s)+'px';c.style.height=(img.height*s)+'px';c.getContext('2d').drawImage(img,0,0)};img.src=src}
function buildPipe(){const p=params();const keys=Object.keys(p).filter(k=>p[k]!==defaults[k] && !['sf','mn','conf','nms'].includes(k));$('pipeList').innerHTML=keys.length?keys.map(k=>`<div class="pipe-item"><b>${names[k]||k}</b><span>${p[k]}</span></div>`).join(''):'<span class="empty">No operations yet</span>'}
function lines(){const n=$('codeEditor').value.split('\n').length;$('lineNumbers').textContent=Array.from({length:n},(_,i)=>i+1).join('\n')}
function setMode(m){state.mode=m;document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.mode===m));$('guiView').classList.toggle('hidden',m!=='gui');$('codeView').classList.toggle('hidden',m!=='code');$('helpView').classList.toggle('hidden',m!=='help')}
document.querySelectorAll('.accordion').forEach(b=>b.onclick=()=>{b.classList.toggle('open');b.nextElementSibling.classList.toggle('hidden');b.querySelector('b').textContent=b.nextElementSibling.classList.contains('hidden')?'›':'⌄'});
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));
document.querySelectorAll('input[type=range],select').forEach(e=>e.addEventListener('input',render));$('fileInput').onchange=async e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=async()=>{state.dataUrl=r.result;state.baseData=r.result;draw(r.result);if(window.editorLoad)await window.editorLoad(r.result);await render()};r.readAsDataURL(f)};
$('canvas').ondragover=e=>{e.preventDefault();$('canvas').parentElement.classList.add('drop-active')};$('canvas').ondragleave=()=>$('canvas').parentElement.classList.remove('drop-active');$('canvas').ondrop=e=>{e.preventDefault();$('canvas').parentElement.classList.remove('drop-active');const f=e.dataTransfer.files[0];if(f){const dt=new DataTransfer();dt.items.add(f);$('fileInput').files=dt.files;$('fileInput').dispatchEvent(new Event('change'))}};
$('runBtn').onclick=async()=>{if(!window.editorExecute)return;try{const out=await window.editorExecute($('codeEditor').value,state.dataUrl);state.baseData=out;draw(out)}catch(e){alert(e)}};$('codeEditor').addEventListener('input',lines);$('clearPipe').onclick=()=>{Object.keys(defaults).forEach(k=>{const e=$(k);if(e)e.value=defaults[k]});render()};$('resetBtn').onclick=()=>location.reload();$('newBtn').onclick=()=>{state.dataUrl=null;$('canvas').width=1;$('canvas').height=1};$('copyBtn').onclick=()=>navigator.clipboard.writeText($('codeEditor').value);$('saveBtn').onclick=()=>{if(!state.baseData)return;const a=document.createElement('a');a.href=state.baseData;a.download='opencv-edited.png';a.click()};$('downloadBtn').onclick=()=>$('saveBtn').click();$('themeBtn').onclick=()=>document.body.classList.toggle('light');window.setStatus=m=>{$('status').textContent='● '+m};window.addEventListener('opencv-ready',()=>{$('cvVer').textContent=window.editorVersion||'ready';$('codeEditor').value=codeFromParams();lines();updateOutputs()});
setTimeout(()=>window.dispatchEvent(new Event('opencv-ready')),1500);
